### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by MomentQYC** [misskey-dev/media-proxy#1]
1.NODE_ENV=production pnpm install
2.Manually run npm start
3.
```
npm WARN config init.module Use `--init-module` instead.

> misskey-media-proxy@0.0.0 start
> fastify start ./built/index.js

SyntaxError: Unexpected strict mode reserved word
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
```
OS:Ubuntu 20.04

**Comment by tamaina** [comment]
What is the version of node.js?

(Note that I am running on v18, but AWS Lambda is v16, so the code must work on v16)

**Comment by MomentQYC** [comment]
> What is the version of node.js?
> 
> 
> 
> (Note that I am running on v18, but AWS Lambda is v16, so I hope the code work on v16)

v18.13.0

**Comment by tamaina** [comment]
I saw that @fastify/static has gone into devDependencies and fixed it, but do you still get the error?

**Comment by tamaina** [comment]
Ah, maybe the following will fix it for sure:
Rewrite config.js following the latest README.md

**Comment by MomentQYC** [comment]
> Ah, maybe the following will fix it for sure: Rewrite config.js following the latest README.md

Sorry, I don't see the difference
Here is my config.js
```js
import { readFileSync } from 'node:fs';

const repo = JSON.stringify(readFileSync('./package.json', 'utf8'));

export default {
    // UA
    userAgent: `MisskeyMediaProxy/${package.version}`,

    // プライベートネットワークでも許可するIP CIDR（default.ymlと同じ）
    allowedPrivateNetworks: ["127.0.0.1"],

    // ダウンロードするファイルの最大サイズ
    maxSize: 20971520,

    // フォワードプロキシ
    // proxy: 'http://127.0.0.1:3128'
}
```

**Comment by MomentQYC** [comment]
I tried to change to a completely new environment and use the config.js inside README.md directly, it still shows the same error.

**Comment by tamaina** [comment]
I have no idea...

**Comment by MomentQYC** [comment]
> わかった、直した

It works,thanks.
