### ISSUE TITLE
CORSヘッダーを付与

### ISSUE THREAD

**Issue by syuilo** [misskey-dev/media-proxy#5]
CORSヘッダーが無いとMisskey Web側で画像のクロップしようとしたときなどにエラーが出る

**Comment by tamaina** [comment]
設定で変更できるようにすればいいかしら？

（Access-Control-Allow-Originに指定したい値はまちまちな感じがある）

**Comment by tamaina** [comment]
CORSっていうかCSPの問題じゃない？

（ここら辺私は苦手だけど）

**Comment by tamaina** [comment]
CORSか

**Comment by tamaina** [comment]
https://techblog.securesky-tech.com/entry/2021/12/09/

*だと解決策にならず、要求のOriginと同じものを返す必要があるらしい

**Comment by tamaina** [comment]
あかんやん

**Comment by tamaina** [comment]
taint canvasになるのは間違いないっぽいんだけど

**Comment by tamaina** [comment]
access-control-allow-origin : * にしてもダメなので詰んだ感じがある？
