### ISSUE TITLE
403の判定が正しくない

### ISSUE THREAD

**Issue by tetsuya-ki** [misskey-dev/media-proxy#7]
README.mdを見ると、以下のように記載されています。
> /proxyは画像ではないと403を返しますが、Media Proxyではそのまま内容を送信します。
https://github.com/misskey-dev/media-proxy/blob/master/src/index.ts#L206

しかし、ソースを見てみると、そうなっていないように見えます。
```typescript
// 画像ではないもの、または、ブラウザセーフでないものの場合NGのような条件に見えます
} else if (!file.mime.startsWith('image/') || !FILE_TYPE_BROWSERSAFE.includes(file.mime)) {
            throw new StatusError('Rejected type', 403, 'Rejected type');
// ----------------------------------------------------------------------------------------
// ブラウザセーフでないものの場合、403返す(こちらの動きが正しい？)
} else if (!FILE_TYPE_BROWSERSAFE.includes(file.mime)) {
            throw new StatusError('Rejected type', 403, 'Rejected type');
```

意図通りではないなら修正したほうがいいと思います。

**Comment by tetsuya-ki** [comment]
@tamaina さん 確認いただくことは可能でしょうか？(画像以外は403が正しい、等ご教示いただけましたら幸いです)

**Comment by tamaina** [comment]
READMEを修正しました:pray:

**Comment by tamaina** [comment]
結局どうして画像だけにしたのか忘れた

**Comment by tamaina** [comment]
画像じゃないものを外部のメディアプロキシでプロキシしても無意味だった気もする（CORSとかの関係で）

**Comment by tamaina** [comment]
バグじゃんなんだこれ…

**Comment by kakkokari-gtyih** [comment]
> 結局どうして画像だけにしたのか忘れた

https://github.com/misskey-dev/misskey/issues/13053#issuecomment-1902161942 負荷がかかるらしい（でもそれはconfigで調整できるようにしたほうが良くね）

**Comment by tamaina** [comment]
> もそれはconfigで切り替えできるように

本体側も改造する必要があるので一旦保留で
